language: r
sudo: false
cache:
  packages: true
  directories:
  - _cache
addons:
  apt:
    packages:
      - gdal-bin 
      - libgdal-dev 
      - libgdal1-dev 
      - netcdf-bin 
      - libproj-dev 
      - libnetcdf-dev 
      - netcdf-bin
git:
  depth: 3
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libgeos-dev libjq-dev libnetcdf-dev libproj-dev libprotobuf-dev libudunits2-dev libv8-3.14-dev netcdf-bin protobuf-compiler
script:
- Rscript -e 'rmarkdown::render_site()'
- Rscript -e 'source("make_sites.R")'
after_success:
- git config --global user.name "Enrique Montes (Travis-CI)"
- git config --global user.email "emontesh@mail.usf.edu"
- git add -A
- git commit -a -m "Updating MBON Pole to Pole data portal via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - ben@ecoquants.com
    - emontesh@mail.usf.edu
    on_success: change
    on_failure: change
env:
  global:
  - secure: BIiJNWS10dtYjj9qQfVQ+Cwo9XWfp6R2uDDTdgdO7Krk+85rNXX9rv4kdZ5DUoeVhSPG6RBgB8T+n++vxrWtDgX+72DxMSsViLpzRue7JLXP/38P4zeAHIxjKmoKdfO//z3YutJ7tFm0VpQx3F7GmLbd4Im27YQ5b66vKOVvyyABYzFj7m/ITj0jmkpiOMNxipR85pTypYkuZ/hbkv6/9i0rvFrQrvt+eCdDzLM9t1btLmdk9tTNKjpdLvosMryKrOfL35a2dOcXo5ZXx+vQP52BUdXkziJCHMR3TGv0xIhy66vj7RZKP0yAjFLrAcpw8+BQrX1e/eoRzpaBBGn8K/Gc58XBOMPdzPgUdr+Zq6jZclsLSGvFOGsEypi6pSGrq26ZqnWQrLuoeIHw0KszZnPXkytdlq+wQrvfjTW46Mgg8Ik5kdQCf254GB8toqbWp7mCdpVLxXUwLyY0fVfumMkK+8qYyPQi4oHQo/lqD1nAephW7tFIkOZ0a0FCbl78oSSqeb4zgjvOZ3aKv+sYG7k5y6fjYu69ZTEUEnePTHjczzWqac/NovEunvm9eFKQwTcLbQO93Hdyt/6nXI0hiJqWci81ds+kjWb2J3jSUC0v/27W4DedBD4rx4fHvapIWQ1O1oWdkuCLaBItbVj3WI3C6ie0UIWzLvQPhnnOe4M=
