language: r
sudo: false
cache:
  packages: true
  directories:
  - _cache
git:
  depth: 3
script:
- Rscript -e 'rmarkdown::render_site()'
- git config --global user.name "Enrique Montes (Travis-CI)"
- git config --global user.email "emontesh@mail.usf.edu"
- git add -A
- git commit -a -m "Updating MBON Pole to Pole data portal via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - bdbest@gmail.com
    - emontesh@mail.usf.edu
    on_success: change
    on_failure: always
env:
  global:
  - secure: i92zgdIhd8OixCHh1CXaxeWxTl12nGAdcUoN7zKra21lEvmOF5xI9sh7LHl0sazUFWIlpDb9nUsigd6jL5bD9gjL3y9Xm9UOhgyrgzGgL+VA8k3FWE+yT3gQ6jrihNQSgIytlTWDdnRiEplqoIXO94nYi3CGOb5KysOosVleCG/LG3XRYdAefYeHI9aA64x/Wfo75WTw9qKTl/iL4RUhT64v0yUhe7bat2RePzWOSdqIVi4yF4aO555p7041Nh0zTptV06qcRuqUnQO+493fMedY9dd8yfP60O3zM3tQsPC2WliMUTrZUasQK7B+7nlfCuz69qDGrU5KApEQQEDxZHAEAwSpxzY3/cV+i8dyTsEcA4o9vPfDclrrVdOcBtFnKLaH3nUmZMM8qbkgVBKnE+m9xKGf3qPEQATFe1Hqidim1jNtu+4DA7TEn/FaRZU29bAssrSmVOl4/D1LYaBIrodq3YKwIqYbGworjW7m7UCfAVlnoljdyT7d3rjLTOUba/nD9Nmo/uRA8bO57rSWWwHNjnD1BFLKGQ2/AKzUVDtc/LrQx0beBFcKnXYiOpAu2VxBItAmwX01ujfbBb8RSIynW/X0NoZcHg96WXTEkxM5uTh8IBWICfnlp9gtzqn0TRWgqpr7Oj0McKM2DwuTx8kFHvrqLRt8vf25hnxH8qg=
